### PR TITLE
update to version 3.19.0

### PR DESCRIPTION
**Pull request by Abdiramen**

### CODE REVIEW

**Review by Alice-Lilith — APPROVED** [review]

**Comment by JohnNiang** [comment]
Hi @Alice-Lilith and @Abdiramen , the latest version(3.19.0) isn't showing in [snap store](https://snapcraft.io/ngrok), please see the following output:

```bash
❯ snap info ngrok
name:    ngrok
summary: ngrok is the programmable network edge that adds connectivity, security, and observability
  to your apps with no code changes.
publisher: Ngrok (ngrok-publisher)
store-url: https://snapcraft.io/ngrok
contact:   https://github.com/ngrok/ngrok-snap
license:   unset
description: |
  ngrok is the programmable network edge that adds connectivity, security, and observability to your
  apps with no code changes.
  
  **ngrok Cloud Edge**
  
  Bring security, scalability, and observability to your apps with ngrok's network edge. No code
  changes required.
  
  **ngrok Secure Tunnels**
  
  Instant access to any system without network pain. No dynamic DNS, port forwarding, and VPNs
  required.
  
  **Regarding: the latest release track**
  
  In the transition to the v3 ngrok agent, we split tracks into `v2` and `v3`. `v3` is the new
  default and hence "true" latest. The `latest` track is left on our `v2` agent for supporting
  legacy customers but may be deprecated in the future.
commands:
  - ngrok
snap-id:      6xrElpxTy49rcoBMvL3HiNp0neq9dOq9
tracking:     v3/stable
refresh-date: 46 days ago, at 11:01 CST
channels:
  v3/stable:        3.18.4 2024-11-11 (226) 11MB -
  v3/candidate:     ↑                            
  v3/beta:          ↑                            
  v3/edge:          ↑                            
  latest/stable:    3.3.5  2023-12-07 (118)  7MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      3.18.4 2024-11-11 (226) 11MB -
  v2/stable:        2.3.40 2022-04-21  (50) 12MB -
  v2/candidate:     ↑                            
  v2/beta:          ↑                            
  v2/edge:          ↑                            
installed:          3.18.4            (226) 11MB -
```

**Comment by Abdiramen** [comment]
@JohnNiang thanks for calling this to my attention! I think i know what happened, and it should be an easy fix.

**Comment by Abdiramen** [comment]
Hey @JohnNiang, just wanted to update you on this. Looks like It's not an easy fix lol. The issue is on snap's side. We're working with them to get it resolved. I'll update here if we're able to get some movement on this.

**Comment by Abdiramen** [comment]
@JohnNiang 3.19.1 release is finally up!

**Pull request merged**
